# Generated by Django 2.2.1 on 2020-04-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='ratio',
        ),
    ]
