# Generated by Django 2.2.1 on 2020-04-08 06:38

import Contest.feild
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_auto_20200404_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrank',
            name='b',
            field=Contest.feild.ListFiled(blank=True, default='[]', max_length=600),
        ),
    ]
