# Generated by Django 2.2.1 on 2020-04-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0003_matchrank_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
    ]
